### PR TITLE
Be more defensive in writing to the sig buffer

### PR DESCRIPTION
**Pull request by hawkinswnaf**

### CODE REVIEW

**Comment by dismantl** [comment]
I like it :)

That was one of the things that made me uneasy when I was looking over it before. Thanks Will!

**Comment by dismantl** [comment]
also, do we need to do pull requests at this point for r1 fixes? Can I just merge this?

**Comment by hawkinswnaf** [comment]
I will leave the larger question/answer up to @jheretic and @areynold, but I tested this particular change and would have no problem with you merging it.

**Comment by hawkinswnaf** [comment]
It was a blessing and a curse that this was not included earlier. The fact that it was writing unchecked the entirety of the returned data from mdp-sign made it "easier" to realize that mdp-sign was sending back more than just the signature.

**Comment by areynold** [comment]
Re: Pull requests, I've been taking it on a case by case basis. As long as the changes are tested, reviewed, and pushed to feature branches, I'm mostly ok not using them. Now that everyone is beginning to scatter for the holidays I would prefer pull requests just because it makes it easier to get lots of eyes on the fixes.

**Pull request merged**
